name: "CI"

on:
  pull_request:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GH_TOKEN }}

      - name: Format check
        run: nix fmt -- --ci

      - name: Install CI dependencies
        run: nix profile add .#ci

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
